#!/bin/bash

if [[ "$#" -lt 2 ]]; then
    echo "usage: fetchContainer containerStorageURL containernametofetch"
    exit 1
fi

wget ${1}/${2}.docker.tar -O - > /tmp/aerContainer$$
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "wget failed: " ${1} ${2}
    exit $retVal
fi


docker load < /tmp/aerContainer$$
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "docker load failed: " ${1} ${2}
    exit $retVal
fi

rm /tmp/aerContainer$$
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "rm failed: " ${1} ${2}
    exit $retVal
fi


exit 0

