#!/bin/bash

if [[ "$#" -lt 1 ]]; then
    echo "usage: fetchContainer containernametofetch" > /dev/stderr
    exit 1
fi

#echo http://people.renci.org/~escott/${1}.docker.tar
wget http://people.renci.org/~escott/${1}.docker.tar -O - | docker load 
