#!/bin/bash
set -x

if [[ "$#" -lt 1 ]]; then
    echo "usage: startContainer containernametofetch" > /dev/stderr
    exit 1
fi

if [ ! -d /var/local"$1" ]; then
    mkdir -p /var/local/"$1"
fi


CONTAINER="$1"

docker run  --privileged -v /dev/bus/usb:/dev/bus/usb -v /var/local/"$CONTAINER":/data "$CONTAINER" 2> /var/local/"$CONTAINER"-stderr > /var/local/"$CONTAINER"-stdout


