#!/bin/bash
set -x

if [[ "$#" -lt 1 ]]; then
    echo "usage: startContainer containernametorun" > /dev/stderr
    exit 1
fi

CONTAINER="$1"

if [ ! -d /var/local/aerpawNodeAgent/"$CONTAINER"/data ]; then
    mkdir -p /var/local/aerpawNodeAgent/"$CONTAINER"/data
fi

docker run  --privileged -v /dev/bus/usb:/dev/bus/usb -v /var/local/aerpawNodeAgent/"$CONTAINER"/data:/data "$CONTAINER" 2> /var/local/aerpawNodeAgent/"$CONTAINER"/stderr > /var/local/aerpawNodeAgent/"$CONTAINER"/stdout < /dev/tty


